# Generated by Django 5.2.8 on 2025-11-08 07:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("workout", "Workout"),
                            ("meal", "Meal"),
                            ("steps", "Steps"),
                        ],
                        help_text="Type of activity",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Activity title", max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="planned",
                        help_text="Current status of activity",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        blank=True,
                        help_text="Duration in minutes (for workouts/meals)",
                        null=True,
                    ),
                ),
                (
                    "calories",
                    models.IntegerField(
                        blank=True, help_text="Calories burned/consumed", null=True
                    ),
                ),
                (
                    "steps_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of steps (for steps activity)",
                        null=True,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now, help_text="Date of activity"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this activity",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="tracker_act_user_id_bcba5c_idx"
                    ),
                    models.Index(
                        fields=["activity_type"], name="tracker_act_activit_9b39ac_idx"
                    ),
                    models.Index(
                        fields=["status"], name="tracker_act_status_8f860c_idx"
                    ),
                ],
            },
        ),
    ]
